# -*- coding: utf-8 -*-
"""AI(DNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsAbeg6gwsF0ECUQUq8xcsKGINJoxkXT

Imports
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import r2_score
import json
import requests
import wandb

layers = tf.keras.layers
EarlyStopping = tf.keras.callbacks.EarlyStopping

DATA_FILE = "paranal_specific_dataset.csv"

PRESSURE_LEVELS = [700, 500, 300, 250, 200]

FEATURE_ORDER = [
    "airmass",
    "pressure",
    "temp_2m", "temp_30m", "temp_ground",
    "temp_gradient_ground_30m",
    "dew_point_depression_2m",
    "wind_speed_10m", "wind_speed_30m",
    "wind_shear_10_30",
    "wind_dir_sin", "wind_dir_cos",
    "wind_w_std",
    "rain_intensity",
    "ir_temperature", "pwv",

    "temp_2m_roll3h_mean",
    "temp_2m_trend_3h",
    "wind_speed_10m_roll3h_mean",
    "wind_speed_10m_trend_3h",
    "wind_speed_30m_roll3h_mean",
    "wind_speed_30m_trend_3h",

    "pressure_trend_3h",
    "wind_w_std_roll3h_mean",
]
TARGET = "seeing"

"""Data"""

try:
    raw_dataset = pd.read_csv(DATA_FILE, encoding="utf-8")
    print(f"data is loaded: {len(raw_dataset)} rows")
except FileNotFoundError:
    raise SystemExit(
        f"{DATA_FILE} is not found"
    )

dataset = raw_dataset.copy()

"""Wandb"""

wandb.init(
    project="seeing-prediction",
    name="DNN-v2"
)

"""Add Feature"""

wind_rad = np.deg2rad(dataset["wind_dir_10m"])
dataset["wind_dir_sin"] = np.sin(wind_rad)
dataset["wind_dir_cos"] = np.cos(wind_rad)

dataset = dataset.sort_values("datetime").reset_index(drop=True)

for col in ["temp_2m", "wind_speed_10m", "wind_speed_30m"]:
    dataset[f"{col}_roll3h_mean"] = dataset[col].rolling(3, min_periods=1).mean()
    dataset[f"{col}_trend_3h"] = dataset[col] - dataset[col].shift(3)

dataset["pressure_trend_3h"] = dataset["pressure"] - dataset["pressure"].shift(3)
dataset["wind_w_std_roll3h_mean"] = dataset["wind_w_std"].rolling(3, min_periods=1).mean()

"""Read Data"""

print("empty cell:")
print(dataset.isna().sum())

valid_subset_cols = [col for col in (FEATURE_ORDER + [TARGET]) if col in dataset.columns]
dataset = dataset.dropna(subset=valid_subset_cols)
print(f"after clean data: {len(dataset)} rows")

dataset["log_seeing"] = np.log1p(dataset[TARGET])
LOG_TARGET = "log_seeing"

"""Clean Data"""

print(dataset.isna().sum())
print(dataset.info())

"""Split the data into training and test sets"""

dataset = dataset.sort_values("datetime").reset_index(drop=True)
dataset["week_block"] = pd.to_datetime(dataset["datetime"], utc=True).dt.to_period("W").astype(str)

blocks_in_order = dataset["week_block"].drop_duplicates().tolist()
n_blocks = len(blocks_in_order)

n_test_blocks = max(1, round(n_blocks * 0.15))
test_blocks = set(blocks_in_order[-n_test_blocks:])
remaining_blocks = blocks_in_order[:-n_test_blocks]

rng_blocks = np.random.default_rng(0)
remaining_blocks = list(remaining_blocks)
rng_blocks.shuffle(remaining_blocks)
n_cv_blocks = max(1, round(len(remaining_blocks) * (0.15 / 0.85)))
cv_blocks = set(remaining_blocks[:n_cv_blocks])
train_blocks = set(remaining_blocks[n_cv_blocks:])

train_dataset = dataset[dataset["week_block"].isin(train_blocks)]
cv_dataset = dataset[dataset["week_block"].isin(cv_blocks)]
test_dataset = dataset[dataset["week_block"].isin(test_blocks)]

bins = [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 100]
print(pd.cut(test_dataset[TARGET], bins=bins).value_counts().sort_index())

"""Inspect the data"""

sns.histplot(data=dataset, x="airmass", y="seeing", cbar=True)
plt.show()

sns.scatterplot(data=dataset, x="wind_dir_10m", y="seeing")
plt.show()

"""Split features from labels"""

x_train = train_dataset[FEATURE_ORDER].select_dtypes(include=np.number).copy()
x_cv = cv_dataset[FEATURE_ORDER].select_dtypes(include=np.number).copy()
x_test = test_dataset[FEATURE_ORDER].select_dtypes(include=np.number).copy()

y_train = train_dataset[LOG_TARGET].copy()
y_cv = cv_dataset[LOG_TARGET].copy()
y_test_log = test_dataset[LOG_TARGET].copy()
y_test_real = test_dataset[TARGET].copy()

wandb.config.update({
    "model": "DNN",
    "n_features": len(FEATURE_ORDER),
    "train_samples": len(x_train),
    "test_samples": len(x_test)
})

"""Normalization"""

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(np.array(x_train))

print(normalizer.mean)
print(normalizer.variance)

"""DNN"""

def plot_loss(history):
  plt.plot(history.history['loss'], label='loss')
  plt.plot(history.history['val_loss'], label='val_loss')
  plt.xlabel('Epoch')
  plt.ylabel('Error [seeing]')
  plt.legend()
  plt.grid(True)

# early_stopping
early_stopping = EarlyStopping(monitor='val_loss',
                               patience=7,
                               restore_best_weights = True)
def build_and_compile_model(norm):
  reg = tf.keras.regularizers.l2(1e-3)
  model = keras.Sequential([
      norm,
      layers.Dense(128, activation='relu', kernel_regularizer=reg),
      layers.Dropout(0.3),
      layers.Dense(64, activation='relu', kernel_regularizer=reg),
      layers.Dropout(0.3),
      layers.Dense(32, activation='relu', kernel_regularizer=reg),
      layers.Dense(1)
  ])

  model.compile(loss='mse',
                metrics=['mae'],
                optimizer=tf.keras.optimizers.Adam(0.001))
  return model

dnn_model = build_and_compile_model(normalizer)

history = dnn_model.fit(
    x_train,
    y_train,
    batch_size=64,
    validation_data=(x_cv, y_cv),
    verbose=0, epochs=1000,
    callbacks= [early_stopping]
)

dnn_model.summary()
plot_loss(history)

"""Performance"""

test_pred_log = dnn_model.predict(x_test, verbose=0).flatten()
test_predictions = np.expm1(test_pred_log)

mae_real = np.mean(np.abs(test_predictions - y_test_real))
mse_real = np.mean((test_predictions - y_test_real) ** 2)
r2 = r2_score(y_test_real, test_predictions)

Error = pd.DataFrame(
    {"loss(MSE)": [mse_real], "MAE": [mae_real], "R2": [r2]}, index=["Test Set"]
)
mae = mae_real
rmse = np.sqrt(mse_real)
print(Error)

"""Make predictions"""

a = plt.axes(aspect='equal')
plt.scatter(test_pred_log, test_predictions)
plt.xlabel('True Values [seeing]')
plt.ylabel('Predictions [seeing]')
lims = [0, 50]
plt.xlim(lims)
plt.ylim(lims)
_ = plt.plot(lims, lims)

# cost function
error = test_predictions - test_pred_log
plt.hist(error, bins=25)
plt.xlabel('Prediction Error [seeing]')
_ = plt.ylabel('Count')

""" Feature importance"""

baseline_pred = np.expm1(dnn_model.predict(x_test, verbose=0).flatten())
baseline_mae = np.mean(np.abs(baseline_pred - y_test_real))

importances = {}
rng = np.random.default_rng(0)
for col in x_train.columns:
    shuffled = x_test.copy()
    shuffled[col] = rng.permutation(shuffled[col].values)
    shuffled_pred = np.expm1(dnn_model.predict(shuffled, verbose=0).flatten())
    shuffled_mae = np.mean(np.abs(shuffled_pred - y_test_real))
    importances[col] = shuffled_mae - baseline_mae

importance_series = pd.Series(importances).sort_values(ascending=False)
print(importance_series)

wandb.log({
    "MAE": mae,
    "RMSE": rmse,
    "R2": r2,

    "batch_size": 64,
    "epochs": 1000,

    "dense_1": 128,
    "dense_2": 64,
    "dense_3": 32,

    "dropout": 0.3,
    "l2": 1e-3
})

wandb.finish()

wandb.finish()

"""Save Model"""

dnn_model.save('dnn_model.keras')
plt.show()